branches:
  only:
    - master

version: 1.0.{build}-rc


configuration: Debug

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

cache:
  - packages


nuget:
  disable_publish_on_pr: true
  
install:
    - cd MiniParser_ParserCombinators
    - nuget restore

    
before_build:
    - ps: pwd
    - ps: dir
     
build:
  project: MiniParser_ParserCombinators.sln
#  verbosity: minimal
  verbosity: detailed

 

  before_deploy:
    - cd coveralls.net\package
    - nuget pack coveralls.net.nuspec -Version "%APPVEYOR_BUILD_VERSION%"
    - ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

  deploy:
  - provider: NuGet
    api_key:
      secure: 2fcbcVHpBbBN9Q9vnWfQaWBpTn0H/5Y10cBMVD1XJuJv5Tcyvcr63lsdAMHJyg61 