version: 1.0.{build}

environment:
    COVERALLS_REPO_TOKEN: 
      secure: eeeee
    
install:
    - cd MiniParser_ParserCombinators
    - nuget restore

    
before_build:
    - pwd
    - dir
     
build:
  project: MiniParser_ParserCombinators.sln
#  verbosity: minimal
  verbosity: detailed


#after_test: 
#    - packages\OpenCover.4.5.3522\OpenCover.Console.exe -register:user -filter:"+[StatePrinter]*" -target:"packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"StatePrinter.Tests\bin\debug\StatePrinter.Tests.dll /domain:single /noshadow" -output:"coverage.xml"

#    - packages\coveralls.io.1.1.86\tools\coveralls.net.exe --opencover "coverage.xml"
    
